version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  laravel:
    build: ./clients-management
    container_name: laravel
    ports:
      - "8000:8000"
    volumes:
      - ./clients-management:/var/www
    depends_on:
      - mysql
    environment:
        DB_CONNECTION: mysql
        DB_HOST: mysql
        DB_PORT: 3306
        DB_DATABASE: laravel
        DB_USERNAME: root
        DB_PASSWORD: ""
    command: sh -c "php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./client-management-frontend
    container_name: frontend
    ports:
      - "8080:8080"
    volumes:
      - ./client-management-frontend:/app
      - /app/node_modules
    depends_on:
      - laravel
    networks:
      - app-network

networks:
  app-network:
